language: cpp

compiler:
  - gcc

branches:
  only:
    - travis

before_install:
  - sudo apt-get install -y cmake libboost-all-dev libeigen3-dev libhdf5-serial-dev

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=Release ..
  - make -j4
